name: atlas
description: "Social media app for humans"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.5.0
  firebase_core: ^3.7.0
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1
  vector_math: ^2.1.4
  cached_network_image: ^3.4.1
  provider: ^6.1.5+1
  video_player: ^2.10.1
  path_provider: ^2.1.5
  image: ^4.0.0
  camera: ^0.10.5+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
   - assets/background_light.png
   - assets/background_dark.png
   - assets/new_map.png
   - assets/edit_previews/0_labels.png
   - assets/edit_previews/1_labels.png
   - assets/edit_previews/2_labels.png
   - assets/edit_previews/3_labels.png
   - assets/edit_previews/4_labels.png
   - assets/edit_previews/5_labels.png
   - assets/edit_previews/6_labels.png
   - assets/edit_previews/7_labels.png