// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVpXV23k1nUKCPvxJFn4BdyxyYH1fghe0',
    appId: '1:1010878433274:web:4360029ef38b1496488643',
    messagingSenderId: '1010878433274',
    projectId: 'atlas-f3082',
    authDomain: 'atlas-f3082.firebaseapp.com',
    storageBucket: 'atlas-f3082.firebasestorage.app',
    measurementId: 'G-HMCG4LRLH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhrM3gqd5K5mfUkwDVuzhsSN5IcGfsbuw',
    appId: '1:1010878433274:android:da7cbd95cc8f9499488643',
    messagingSenderId: '1010878433274',
    projectId: 'atlas-f3082',
    storageBucket: 'atlas-f3082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC07bCQjMfH11pxVFaYVk6Ek6CL9n4t8Sk',
    appId: '1:1010878433274:ios:06dfe450e4d63c6f488643',
    messagingSenderId: '1010878433274',
    projectId: 'atlas-f3082',
    storageBucket: 'atlas-f3082.firebasestorage.app',
    iosBundleId: 'com.example.atlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC07bCQjMfH11pxVFaYVk6Ek6CL9n4t8Sk',
    appId: '1:1010878433274:ios:06dfe450e4d63c6f488643',
    messagingSenderId: '1010878433274',
    projectId: 'atlas-f3082',
    storageBucket: 'atlas-f3082.firebasestorage.app',
    iosBundleId: 'com.example.atlas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVpXV23k1nUKCPvxJFn4BdyxyYH1fghe0',
    appId: '1:1010878433274:web:40e3da0957b306fd488643',
    messagingSenderId: '1010878433274',
    projectId: 'atlas-f3082',
    authDomain: 'atlas-f3082.firebaseapp.com',
    storageBucket: 'atlas-f3082.firebasestorage.app',
    measurementId: 'G-3W8BL8TMQR',
  );
}